### ISSUE TITLE
After upgrade from 2.4.13 to 2.5.1 installation in subfolder is broken

### ISSUE THREAD

**Issue by kiwi-x** [linuxserver/ifai#1031]
Hello,

I've installed heimdall in a subfolder of my server, ie. https://web.local/heimdall

After updating from 2.4.13 to 2.5.1 the installation is broken, 'cause the 
pathes to for app.js, app.css and backgroudn image are set to root.

instead /heimdall/js/app.js      it is linked to /js/app.js, 
             /heimdall/css/app.css it is linked to /css/app.css
             /heimdall/img/            it is linked to /img/

kiwi-x

**Comment by KodeStar** [comment]
Should be fixed in 2.5.2, let me know

**Comment by kiwi-x** [comment]
Hi - I just saw the release notification and installed it - and yes it's fixed! 

Thank you
Kiwi-x
