### ISSUE TITLE
Application doesn't show at Heimdall's index page

### ISSUE THREAD

**Issue by tyultra** [linuxserver/ifai#1032]
I added 6 applications to the list, but only No.1~No.5 can show at index page. 
No.1~No.5 can find the application names in the textfield, while No.6 doesn't exist in the list (but accessible via browser).
![image](https://user-images.githubusercontent.com/36122504/203969868-c90a39e9-9b89-4766-84bd-e8fd00145536.png)

**Comment by keriati** [comment]
Is the application pinned in the setting page of that item?

**Comment by tyultra** [comment]
No, I can't find it in the setting.















--

Tony Yu
***@***.***




At 2022-11-26 00:12:50, "Attila Kerekes" ***@***.***> wrote:

Is the application pinned in the setting?

**Comment by KodeStar** [comment]
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/5698566/204088071-f1dfbdee-e547-473c-b29c-97bca865f9e4.png">
Make sure the application is set to pinned.

**Comment by tyultra** [comment]
Yes, it is. The Heimdall version is 2.4.13.















--

Tony Yu
***@***.***




At 2022-11-26 20:07:29, "KodeStar" ***@***.***> wrote:

Make sure the application is set to pinned.

**Comment by KodeStar** [comment]
> Yes, it is. The Heimdall version is 2.4.13.

Maybe try with the latest release? Currently 2.5.3

**Comment by tyultra** [comment]
I am currently using a docker version heimdall. I've got the latest image of heimdall and ran again, still it is 2.4.13, nothing has changed.




--

Tony Yu
***@***.***




At 2022-11-28 16:35:49, "KodeStar" ***@***.***> wrote:

Yes, it is. The Heimdall version is 2.4.13.

Maybe try with the latest release? Currently 2.5.3

**Comment by keriati** [comment]
@tyultra some update I guess didn't work, on docker the latest is 2.5.3, see https://hub.docker.com/r/linuxserver/heimdall/tags?page=1&ordering=last_updated&name=2.5
