### ISSUE TITLE
[bug] transparent color gets reset

### ISSUE THREAD

**Issue by PhilippMundhenk** [linuxserver/ifai#1035]
For design reasons, I do not define any color for any of my tiles (i.e., delete all text in color filed, including #), which gives them a nice transparent effect. However, whenever I edit a tile, the color setting is reset to the default (usually #161b1f) and I need to manually delete the color before saving.

**Comment by KodeStar** [comment]
Your best bet is to hide it with custom css in the settings in that case, something like:
```
.item {
    background-color: transparent!important;
}
```
If you wanted to hide the titles as well you could use:
```
.item .details .title {
    display: none;
}
```

**Comment by PhilippMundhenk** [comment]
I was not refering to th title color, but rather the background-color of .details. This can be set in the settings of every app. Example:
![grafik](https://user-images.githubusercontent.com/4414560/204083593-de2c0b51-e86d-4016-a583-7e2e6fc24d2f.png)

I delete this color, to achieve a transparent background and white text and arrow. This works very well:
![grafik](https://user-images.githubusercontent.com/4414560/204083148-f5d326ce-ab6b-4757-bad6-02adf50fdab7.png)

However, when opening the settings again, the color is reset to the original value.
I tried setting it to "transparent", which unfortunately results in black text:
![grafik](https://user-images.githubusercontent.com/4414560/204083124-9b7ae1ff-ed28-45e9-a844-ba548cd84422.png)

However, the hint with custom CSS and some poking around let me to achieve what I want through:
```
.item {
    background-color: transparent !important;
}
.item .link {
    color: #ffffff !important;
}
.item .details .title {
    color: #ffffff !important;
}
```

I will leave this closed, but resetting a setting of the user still feels like a bug...

**Comment by KodeStar** [comment]
It doesn't know it's a user setting though, it just sees an empty value. The other option is to add an alpha channel, something like #00000000 (so 8 zeros instead of 6), which will do the same thing and shouldn't get reset either
