### ISSUE TITLE
Option to disable blur effect

### ISSUE THREAD

**Issue by Gummibaer** [linuxserver/ifai#1042]
Please add an option to disable the blur effect when clicking on an element.
Or tell me how to disable this

**Comment by shakasan** [comment]
I totally agree as well, this is "beautiful" (not in my opinion, other CSS effects would be more WoW), however, when you are using Heimdalll as dashboard for something supposed to be productive, you feel like working in slow motion.
And if you CTRL+Click to open an app from Heimdall in background, it's requiring an additional click to come back to normal state OR you have to guess where is the other app you want to open and blindly click on it...
Eye Candy is fine, when it's not disturbing the main purpose of the app.
So definitely, an option to disable it, or an other, less disturbing, effect should be used are really necessary.

**Comment by keriati** [comment]
I think in the next version the effect should remove itself after ctrl+click.

**Comment by KodeStar** [comment]
Should be fine in 2.5.3. The blur effect is mainly for keyboard navigation to make it clear which item is highlighted (when using tab to cycle through tiles).
