### ISSUE TITLE
Request PBS as App

### ISSUE THREAD

**Issue by Serpensin** [linuxserver/ifai#1046]
Hi,
I would like to have the PBS (Proxmox Backup Server) as App like PVE, so I can check space left, cpu, ram, etc.

**Comment by keriati** [comment]
I recommend checking: 
- https://github.com/linuxserver/Heimdall-Apps/wiki/Requesting-Apps
- https://github.com/linuxserver/Heimdall-Apps/wiki/Submitting-an-app
