### ISSUE TITLE
qBittorrent API doesn't work with the last version

### ISSUE THREAD

**Issue by barzag** [linuxserver/ifai#1055]
Hello,

Following the Heimdall update, the qBittorrent API no longer works? Any idea for a fix?

**Comment by joeinertia** [comment]
was wondering if this was just me too, do you get any result when testing? unresponsive for me

**Comment by keriati** [comment]
It could be a known bug in 2.5.3, what version do you have?

**Comment by barzag** [comment]
v2.5.3

**Comment by Llamrei80** [comment]
This is a duplicate of #1050 and is fixed in the development build.
