### ISSUE TITLE
Add new application type

### ISSUE THREAD

**Issue by AleixMT** [linuxserver/ifai#1069]
I would like to add new options for the "Application type" menu. The programs that I want to add are:
- Chemotion
- Signals notebook
- iochemBD
- Dataverse

I think is only adding data, but I do not know how. Can you tell me how can I add these configurations? I will raise a PR when I have my changes.

Thank you! Heimdall is wonderful :dancing_men:

**Comment by keriati** [comment]
@AleixMT I recommend checking the wiki on the Apps page: https://github.com/linuxserver/Heimdall-Apps/wiki/Submitting-an-app

**Comment by AleixMT** [comment]
Thank you so much, I will submitt my PR ASAP!
