### ISSUE TITLE
pihole enhanced new api

### ISSUE THREAD

**Issue by chiragkrishna** [linuxserver/ifai#1083]
there is pihole [update](https://pi-hole.net/blog/2022/12/21/pi-hole-ftl-v5-20-and-web-v5-18-released/#page-content) and changes in the pihole [api](https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/) if the pihole is password protected.
the default url no longer works to get the data
```
http://pi.hole/admin/api.php
```

according to the devs of pihole we can use these but heimdall doesn't seem to get the data

```
http://pi.hole/admin/api.php?summary&auth=<TOKEN>

or

http://pi.hole/admin/api.php?summaryRaw&auth=<TOKEN>
```
get the token from Settings/API/Show API token

**Comment by keriati** [comment]
Tracked here: https://github.com/linuxserver/Heimdall-Apps/issues/579
Closing this issue.
