### ISSUE TITLE
Kubernetes Deployment Latest vs 2.5.4 tag

### ISSUE THREAD

**Issue by welshname** [linuxserver/ifai#1087]
When deploying Heimdall in K8S there is an issue whereby using the "latest" tag breaks the app since the latest update, but using the "2.5.4" tag works perfectly fine.

Is there any reason for this?  Latest is "2.5.4" as far as I'm aware?

The output is that the container thinks everything is fine, but navigating to the URL gives you a "file not found" error.

**Comment by gustavomagella** [comment]
Same here bro. I hope somebody fix this. ;)

**Comment by aptalca** [comment]
Wrong repo
Try https://github.com/linuxserver/docker-heimdall
