### ISSUE TITLE
edit SERVER ERROR

### ISSUE THREAD

**Issue by iamckun** [linuxserver/ifai#1089]
Error 500 when opening edit
![image](https://user-images.githubusercontent.com/65990499/210294970-6ea1c52a-88fb-41c7-94e0-a9c0817701ce.png)

**Comment by keriati** [comment]
The edit page seems to work without issues in the latest release. Please include more details in future tickets.

**Comment by iamckun** [comment]
> The edit page seems to work without issues in the latest release. Please include more details in future tickets.

this's all，Click Edit, that's it

**Comment by xtianpaiva** [comment]
same issue here, can not edit some apps on v2.5.5

**Comment by keriati** [comment]
> same issue here, can not edit some apps on v2.5.5

After update if some apps can't be edited it might be because they got an incompatible update, I suggest to try to add them newly again and delete the old one. 
Please let me know if this works.

**Comment by OBoudreaux** [comment]
Deleting the old app and adding it again doesn't work. So far I've seen this with Portainer and traefik.
