### ISSUE TITLE
openmediavault 

### ISSUE THREAD

**Issue by doomboy2020** [linuxserver/ifai#1093]
openmediavault enhanced apps not showing any stats after upgrading to the latest openmediavault

**Comment by raulfg3** [comment]
confirmed, same behaviour here. 

<img width="335" alt="image" src="https://user-images.githubusercontent.com/12611785/211197999-33143901-f911-42b8-a961-131254c172ff.png">

**Comment by northernpowerhouse** [comment]
likewise

All latest, heimdall on docker on a remote host, omv on same subnet, tried with ro user and even my main admin user, no success.

**Comment by raulfg3** [comment]
Hello, ¿nobody are interested on this?

still do not work

**Comment by keriati** [comment]
I was checking out if there was any change recently on openmediavault side, but could not find anything changed in the rpc file: 

https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/var/www/openmediavault/rpc/session.inc

Also in the heimdall apps there was no change with the openmediavault plugin...

@raulfg3 how did you get this $password error?

**Comment by raulfg3** [comment]
error appear when I push the "test" button, but now , I can re-test, and error dissapear, message was the expected: "Sucesfully comunicated with the API", but still do not show statics like CPU or RAM Usage.
![1](https://user-images.githubusercontent.com/12611785/213408394-0156b8f0-20e3-45fb-baa7-271d1e83748c.jpg)

![2 ](https://user-images.githubusercontent.com/12611785/213408756-fa0627e3-cbe0-41fa-8556-8970efb90ac1.jpg)

**Comment by acalisesi** [comment]
I have the shame issue. I upgraded openmediavault to 6.2.0 and Heimdall app doesn't show any stats. the answer of js call is 500 server error.

**Comment by acalisesi** [comment]
I found this error in laravel log file: 
`[2023-02-27 14:22:38] local.ERROR: Undefined property: stdClass::$pkgUpdatesAvailable {"except
ion":"[object] (ErrorException(code: 0): Undefined property: stdClass::$pkgUpdatesAvailable at
 /config/www/SupportedApps/openmediavault/openmediavault.php:87)
[stacktrace]
`
There is a mismatch property name in the function livestats().
I think that it's the issue in the call of openmediavault rpc api.

**Comment by raulfg3** [comment]
any news?, some update to see statics are welcome.

**Comment by keriati** [comment]
Fix was merged.
