### ISSUE TITLE
Docker Error

### ISSUE THREAD

**Issue by zee00100** [linuxserver/ifai#1097]
Hi All,

Love using Heimdall!  I run a Docker setup and also watchtower to auto-update the docker image.  Since a few days ago Heimdall isn't working.   After checking the logs through portainer it's throwing this error:

  thrown in /app/www/artisan on line 18
PHP Warning:  require(/app/www/vendor/autoload.php): Failed to open stream: Permission denied in /app/www/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/app/www/vendor/autoload.php' (include_path='.:/usr/share/php8') in /app/www/artisan:18

Stack trace:

}

Any ideas as to what's going on?

I am using the following image:

Linuxserver.io version:- v2.5.5-ls198 Build-date:- 2023-01-09T20:39:10+01:00

Thanks!

**Comment by keriati** [comment]
@zee00100 did you figure out the problem?
On my side 2.5.5 did not have any issues so far.

**Comment by zee00100** [comment]
I recreated the container and pulled the latest image.  It managed to fix the issues.  I think it might have been a corrupted image or something along those lines.
