### ISSUE TITLE
Your Composer dependencies require a PHP version ">= 7.4.32". You are running 7.4.3

### ISSUE THREAD

**Issue by AIO-Software-tech** [linuxserver/ifai#1098]
when i run ` php artisan serve --host=10.20.4.200 --port=80 `

I get this error :

Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 7.4.32". You are running 7.4.3.

PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.32". You are running 7.4.3. in /home/pi/Heimdall-2.5.5/vendor/composer/platform_check.php on line 24

I have tryed updating php do you have any other sugestions

**Comment by aptalca** [comment]
> I have tryed updating php do you have any other sugestions

You need to update php. That is the only solution

**Comment by jamieduk** [comment]
iv got same isue, i have tried using new php and it stops the secure pages loading only insecure web pages work when i mess with php version, im totally stuck!

**Comment by keriati** [comment]
What operating system are you on?
if 7.4.32 is not available for your system, some php 8 version could also work.
