### ISSUE TITLE
Heimdall docker immediately closes with "unable to iopause: Operation not permitted"  

### ISSUE THREAD

**Issue by Bellerophon787** [linuxserver/ifai#1099]
Here is the log file from docker:

s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted

I really have no idea what I'm doing wrong. Any help is greatly appreciated.

**Comment by thespad** [comment]
https://docs.linuxserver.io/faq#libseccomp
