### ISSUE TITLE
Tautulli API communication successful, but stream status not updating on dashboard

### ISSUE THREAD

**Issue by mysterious1der** [linuxserver/ifai#1100]
Heimdall 2.5.5 and Tautulli 2.11.1. Both running on a macvlan network with no firewalls between them. Tautulli API key login successful.

On the Heimdall dashboard, the Tautulli tile says "0 stream count". When I click to launch Tautulli it (accurately) reports 1 current stream.

I looked at logs for both containers and didn't see anything pertinent to include here, but I'm happy to provide logs.

**Comment by keriati** [comment]
Hi, on my side the stream count in Tautulli is updating correctly, however only every 20 seconds or so.

**Comment by mysterious1der** [comment]
Ok, if it's just something on my side then that's fine.
