### ISSUE TITLE
When NginxProxyManager enable is enabled, edit the error

### ISSUE THREAD

**Issue by thsrite** [linuxserver/ifai#1106]
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/54088512/214863282-c32b6d35-464c-4ac6-b31e-1572943ea8f1.png">
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/54088512/214863327-ad5815a3-9328-4da6-a10e-4683a469270c.png">
Application Type selects NginxProxyManager, and then enables

**Comment by hackitz** [comment]
so i'm getting the same error.
it started for me when i re arranged the tiles. (possible and update happened around the same time)
i have 3 tiles that dont work, OMV, Portainer and UNFI.
i get the error when i try to edit the settings for any of the apps.
i have removed them, updated app list, then added them back. still they are not responsive to clicking them to open.
