### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'o.length') - app.js:650

### ISSUE THREAD

**Issue by dtmichel** [linuxserver/ifai#1108]
I am trying to set up the application of "Gitlab" and the optional config data. After entering the two keys and pressing the "Test" button I can see a javascript error:

`TypeError: undefined is not an object (evaluating 'o.length')`

When looking at the line 650
`o.length && "" !== o && (i = o);`
and debugging it it appears that 'o' is 'undefined'. There is no field '#sapconfig input[name="config[override_url]"]', therefor 'o' is set to 'undefined'. All code after that line is not executed, the button "Test" doesn't do anything more.

Using the latest docker image from Docker Hub.

**Comment by keriati** [comment]
After the above fixes I recommend trying again.
You can get the gitlab app fix by triggering update apps and adding gitlab again.
However the heimdall fix will only be available in the `development` version of the heimdall docker image, so you would need to update to that or wait for the next release (that could take some weeks).
