### ISSUE TITLE
Userselect page is not responsive

### ISSUE THREAD

**Issue by koozma** [linuxserver/ifai#1109]
I've encountered an issue with the userselct page, where it's impossible to select the first user in the list if there are 4 users on mobile devices. Basically all users stay in one row, and are not moved down when shrinking the browser width.
With my limited knowledge, I believe flex-wrap: wrap; is missing from .userlist in css

**Comment by keriati** [comment]
Thanks for the report, I try to take a look soonish.

**Comment by wr-lang** [comment]
Same problem on desktop with 14 users. New line in `resources/assets/sass/_app.scss:225` aka `app.css` with `flex-wrap: wrap;` fixed it.

Thank you for that great work!
