### ISSUE TITLE
OpenMediaVault- needs Skip TLS verification

### ISSUE THREAD

**Issue by MnM001** [linuxserver/ifai#1114]
Hi,

I have a local generated SSL certificate on my OMV.
When configuring OMV enhanced app in Heimdall I get an error about about the local certificate.
It doesn't show any stats.

Will be good to have a Skip TLS verification - sort of like Proxmox enhanced app does.

Thanks

**Comment by ntaylor-86** [comment]
Hey @MnM001,

Does this modification work for you?

https://github.com/ntaylor-86/Heimdall-Apps/commit/98a11c9aaaaf508ba8dc24503a30d489cd417dd8

**Comment by MnM001** [comment]
Edit - found the location. Getting the files now.

I have Heimdall running in a Docker container. 

I could SSH in the Docker container but I don't the path where these files are located in.
I guess if I know that then I get do a wget and putt your files in and see.

**Comment by MnM001** [comment]
Got this error when trying to configure OpenMediaVault atfter i got the files in:

ParseError
syntax error, unexpected token "," (View: /config/www/SupportedApps/openmediavault/config.blade.php)

**Comment by ntaylor-86** [comment]
I'll have to spin up a copy and test it out
