### ISSUE TITLE
Update from 2.4.13 to 2.5.5 failed

### ISSUE THREAD

**Issue by geraldurbas** [linuxserver/ifai#1119]
Followed Update Instructions.
Result was:
- Language list empty
- Some Save action (Userpassword and Apps) produced 419 PAGE EXPIRED Laravel messages.

**Comment by matclou** [comment]
Hi! I am facing similiar problems: I installed version 2.5.7 on TrueNAS Core as a plugin (see https://github.com/jsegaert/iocage-plugin-heimdall). The language list is not completely empty, but it contains only the English language. I am not 100 % sure whether this is the same error.

I also tried to replicate the 419 error by setting a user password, but at my instance everything worked.
