### ISSUE TITLE
Heimdall doesn't show stats (some do work)

### ISSUE THREAD

**Issue by Anilo1990** [linuxserver/ifai#1129]
I'm using Heimdall V2.5.6 in Docker on a Synolgy NAS.
Some applications show stats (e.g. Paperless-NGX or Portainer) and some doesn't (Jellyfin, Speedtest-Tracker, FritzBox).
In Speedtest-Tracker I click on the test button and I get a response with "Successfully communicated with the API" but no stats are visible.

Is this a known issue or is there a way to manually fix it?

![2023-03-11_firefox_7aBeJdv8qt](https://user-images.githubusercontent.com/16625964/224492830-7fc22732-1f8e-4861-b782-6653183e6256.png)

![2023-03-11_firefox_6XYjdMPqnp](https://user-images.githubusercontent.com/16625964/224492618-0385bd57-c9a3-447f-b246-10ac356a6240.png)

**Comment by bfilitz** [comment]
I had to select some items in the 'stats to show' list before the widgets showed anything.
