### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by dyimo** [linuxserver/ifai#1131]
Under the latest version of docker 2.5.6, when starting a service and creating a new one, sometimes it can be added normally, but occasionally the addition fails, and the addition failure directly leads to a 500 error in the entire App access, and only restarting the container can Recovery, 500 appears again after a period of time, check the log and find the following.

nginx log:
![image](https://user-images.githubusercontent.com/10841232/225917586-53b3ee21-e209-43f3-bf89-53b44e32a96c.png)

www logs:
![image](https://user-images.githubusercontent.com/10841232/225917876-48c8900c-5472-44db-ab9c-cbec1cb81504.png)

**Comment by dyimo** [comment]
www logs:
![image](https://user-images.githubusercontent.com/10841232/225918388-de5a2348-2fcb-404c-b798-678c10983c94.png)

**Comment by keriati** [comment]
seems like the applist is not reachable and this causes some error :/

**Comment by DeserranoJorden** [comment]
Having the same issue here when trying to add new apps

**Comment by DeserranoJorden** [comment]
Seems to be an undefined array key?

`[2023-04-06 10:25:14] local.ERROR: Undefined array key "extension" {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key \"extension\" at /app/www/app/Http/Controllers/ItemController.php:228)
[stacktrace]
#0 /app/www/app/Http/Controllers/ItemController.php(228): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /app/www/app/Http/Controllers/ItemController.php(292): App\\Http\\Controllers\\ItemController::storelogic()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\ItemController->store()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#6 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#7 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 /app/www/app/Http/Middleware/CheckAllowed.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /app/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckAllowed->handle()
#10 /app/www/app/Http/Controllers/Controller.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()`

**Comment by Landshark77** [comment]
> Having the same issue here when trying to add new apps

I blocked the heimdall_session cookie and it fixed this error for me.  As soon as I unblock the cookie, I get the 500 error again.
