### ISSUE TITLE
How to hide bottom right menu from anonymous user ?

### ISSUE THREAD

**Issue by gamersalpha** [linuxserver/ifai#1136]
Hello there, 

how to hide this : 
![image](https://user-images.githubusercontent.com/32466950/227801093-a9cdefe4-8e2a-4098-b092-c10170b04190.png)

to all user and anonmyous, and let only the admin get this  ?

i use this config : 

![image](https://user-images.githubusercontent.com/32466950/227801159-14f7578e-9a6c-450c-a56d-bdd26646a248.png)

so anonymous can't connect but they see the menu

thanks all

**Comment by gamersalpha** [comment]
up

**Comment by nicedevil007** [comment]
up
