### ISSUE TITLE
Quick search

### ISSUE THREAD

**Issue by HyP3r-** [linuxserver/ifai#1145]
We use Heimdall in our IT team to manage our internal and external web systems. It would be nice if there was something like a quick search if you don't know by memory which tag the system is in.

**Comment by keriati** [comment]
We have a quick search for the current screen at the moment. Would you like to have it extended to all tag pages?

**Comment by HyP3r-** [comment]
Yes I would like to have this function extended to all tag pages. For example, if my colleague is sorting something and I don't know where it went, it would be great to be able to search for it quickly.
