### ISSUE TITLE
Import - is it supposed to overwrite all ?  (it does not)

### ISSUE THREAD

**Issue by bob454522** [linuxserver/ifai#1159]
i updated to ver 2.5.6 ,  i did the (NICE NEW feature!) of:  settings-> export,  made some changes,  and then imported that changed JSON file,  and now i have duplicates of all my entries.
(clearly the import, added/merged, not replaced, the existing entries).

is this the intended behavior of the import function?

(i could not find any info / documentation on it).

I was able to swap out my sqlite file to a backup (to revert the duplicates) - but i just wanted to confirm Import is running correctly.

(and if it is, there should be a note or warning on the import screen as to what actions import will take).

thanks!

**Comment by keriati** [comment]
Import should not delete / overwrite existing items.
