### ISSUE TITLE
Possible to add custom routes?

### ISSUE THREAD

**Issue by nitinthewiz** [linuxserver/ifai#1162]
Hi,

I'm curious if heimdall can do more than just hold a list of apps on my network. Can it also point to them?

Basically, if I am hosting heimdall on server.local, I can currently go to server.local and then click on the application I want to go to.

Instead, can I add a custom route which would allow me to put in "server.local/rss" and that'll redirect me to my local FreshRSS installation? (FreshRSS is one of my internal apps)

If it's not currently possible, could we look into this as a feature request?

Pros - 
Much easier navigation, one less step (unless heimdall is your homepage)

Cons - 
Very easy to override heimdall internal routes, unless designed to not allow that.

**Comment by j0nnymoe** [comment]
Heimdall isn't designed to do the routing itself, it's just redirecting you to the links you put in. If you want url's like that, use an internal reverse proxy.

**Comment by nitinthewiz** [comment]
Good point @j0nnymoe. Thanks for reminding me to set one up. I also noticed that the README talks about setting up a proxy and heimdall specific stuff there.
