### ISSUE TITLE
update APP_URL use nginx proxy

### ISSUE THREAD

**Issue by iamckun** [linuxserver/ifai#1165]
.evn file APP_URL="https://domain/heimdall"
Request exception
Can heimdall be proxied in some way so that it does not occupy the root directory of the domain name

**Comment by Tchoupinax** [comment]
Hello,

I meet the same issue, while looking in the code the `APP_URL` should do the job

**Comment by Tchoupinax** [comment]
I tested locally and I saw that for assets, it should be `ASSET_URL` to be edited.
However, it seems that environment variable do not override what is taken from `.env`.
https://github.com/linuxserver/Heimdall/issues/848

Edited directement `ASSET_URL` on the volume worked.

**Comment by iamckun** [comment]
@Tchoupinax 

> I tested locally and I saw that for assets, it should be `ASSET_URL` to be edited. However, it seems that environment variable do not override what is taken from `.env`. #848
> 
> Edited directement `ASSET_URL` on the volume worked.
Are you able to access the subdirectory now？

**Comment by Tchoupinax** [comment]
@iamckun yeah it worked by editing the configuration directly on the volume. But today, I want to do this with Kubernetes and it's another way that just having a Docker container with a shared volume. It's still not possible to configure this path via an environment variable?
