### ISSUE TITLE
Heimdal on Portainer wont install missing img.

### ISSUE THREAD

**Issue by StianNOR** [linuxserver/ifai#1168]
Heimdal on Portainer wont install missing img. Please help or update something hahahaha ;)

**Comment by StianNOR** [comment]
![image](https://github.com/linuxserver/Heimdall/assets/82333847/c9022e90-0bf3-4810-897b-aaa84fd64c61)

**Comment by j0nnymoe** [comment]
We don't provide those templates nor do we support/recommend portainer.

**Comment by aptalca** [comment]
You need to contact whoever is maintaining those templates, or portainer.
