### ISSUE TITLE
Support multiple sections

### ISSUE THREAD

**Issue by ileodo** [linuxserver/ifai#1175]
Hey, is that aligned with the product vision here to support multiple sections on the dashboard, so the apps can be put under different sections. thanks

**Comment by amasolini** [comment]
I second this. It would be amazing if we could have a single dashboard with multiple groups/sections being displayed, with their corresponding icons/elements in the, similarly to what Homarr does (check the example)

This could be archieved by having a setting to show, in the main dashboard, things grouped by TAGS other than "Home dashboard"

Example of my Homarr dashboard with multiple groups of applications/sites.
![image](https://github.com/linuxserver/Heimdall/assets/5497345/c082b5dc-0f42-43a9-b32a-8dffbe799315)

**Comment by lloydbayley** [comment]
Agreed! If columns were worked into this, you'd have the market over Homer. Visual config is already one up on Homer, this would be the icing on the cake!

**Comment by awonglk** [comment]
This was requested before way back in 2019.. 
https://github.com/linuxserver/Heimdall/issues/352

But doesn't look like it will be considered.
I would also love to see this implemented.

**Comment by lloydbayley** [comment]
I agree, it's a shame. I've been exploring Dashy. I didn't like it at first because I didn't like the high-contrast colourschemes that everyone seems to have but I found the Material theme was fairly-pleasing.

**Comment by masterlog80** [comment]
+1 It would be a nice feature to group all applications per use (e.g. Network, Internet, URLs, etc.).

**Comment by XobSod** [comment]
+1

**Comment by silycr** [comment]
+1

**Comment by markkastoun** [comment]
+1

**Comment by FrancoTampieri** [comment]
+1

my 2 cents

Well grouping is very usefull, but maybe good to have another feature, like a folder where u can set an icon for example "Virtualization" and clicking on it u can open a page of your virtualization apps

Kind regards

Franco Tampieri

**Comment by godsgood33** [comment]
I am using Heimdall as a start/new tab page and grouping is critical to me for that use so I built a wrapper for Heimdall to accomplish that.

**Comment by XobSod** [comment]
@godsgood33 are you able to share your solution? :D i am not very good at frontend development ;)

**Comment by godsgood33** [comment]
> @godsgood33 are you able to share your solution? :D i am not very good at frontend development ;)

I'm not very good with frontend either.  I'm almost done with it. I'll try to respond this weekend and give you the info.

**Comment by godsgood33** [comment]
@XobSod I had some time...https://github.com/godsgood33/heimdall-wrapper ...let me know what you think

**Comment by pwannenmacher** [comment]
+1

**Comment by mschulze46** [comment]
+1

Grouping support like in Homer/Dashy/etc would be such a huge step forward!!!
