### ISSUE TITLE
Error "Icon must be an image." when attempting to create some appliction Launcers

### ISSUE THREAD

**Issue by mattbaker109** [linuxserver/ifai#1179]
OS: Debain 12 and Ubuntu 22.04. PHP v7.4.33. Heimdall version: 2.5.7 

After a fresh install, attempt to add a new Launcher for Proxmox or Syncthing. Once hitting the save button get an error: "Icon must be an image." and the launcher will not save.

**Comment by mattbaker109** [comment]
Revert to version 2.5.6  and application is working as expected.

**Comment by Anarch157a** [comment]
My workaround is to right-click on the displayed icon, save the image then re-upload it. But it's annoying.

**Comment by allw1994** [comment]
Issue for me too, best I can tell the Store@ItemController method is receiving the correct url and will work if the image is a .png but if it is .svg it does not work.

**Comment by GJSchaller** [comment]
Issue for me as well - Heimdall 2.5.7, Rocky Linux 9.2, Apache 2.  Issue happens with both links to external websites, and pre-defined Apps.

**Comment by allw1994** [comment]
Anyone come across a solution to this?

Starting to annoy me the number of steps to get a single link to work and the fact the integrations don't work.

**Comment by allw1994** [comment]
Still waiting on PR merge #1222

**Comment by ovhelemann** [comment]
I have the same issue on version 2.5.7  (docker)

**Comment by abhisheknair** [comment]
Facing same issue with v2.5.7 (docker)

**Comment by ipnetxyz** [comment]
I've noticed that if I add a new app  and it has an image which is .png type, all is good. If the image is .svg, I need to download it and upload like mentioned above.

**Comment by jonaavanza** [comment]
I have the same issue with the latest docker image

**Comment by pmontgo33** [comment]
Also having this issue running version 2.5.7 in a Debain Bookworm LXC on Proxmox.

**Comment by Halfang** [comment]
Having the same issue with docker 2.5.7 
Linuxserver.io version:- v2.5.7-ls237 Build-date:- 2023-10-27T18:31:16+00:00

**Comment by konradmazurczak** [comment]
same here
BUILD_DATE=2023-10-27T18:31:16+00:00 VERSION=v2.5.7-ls237 HEIMDALL_RELEASE=v2.5.7

**Comment by ADIX7** [comment]
Same here

**Comment by meminens** [comment]
Same here. Downloading the icon and re-uploading appears to be working.

**Comment by arnovdk** [comment]
All, I would say there doesn't seem necessary to further post anymore "Me 2!" messages. We all see that the problem exists and that an effective work-around has been suggested.

I subscribed to this thread so that I might stay informed about any progress, but getting notifications for these messages really isn't adding or helping. If you haven't considered it, you could help out by investigating the bug and discovering a possible solution. But as is the case with me (and possibly the maintainers of this project), time is scarce and also maybe like me, maybe you lack the skills to do so. So for me the work-around helps for now, until the solution presents itself. 🙂

Thank you for your consideration!

**Comment by allw1994** [comment]
The work arounds don’t give full functionality though. 

Downloading and reuploading the image means you can’t use the integrations.

Changing the controller as per PR #1222 breaks other things.

I’ve been looking at this myself and without the PR and further changes we are stuck but they still haven’t approved the PR or made comment on suggestions as to how to fix any of the bugs in the PR.

**Comment by ZoltrixGFC** [comment]
Also have seen the same issue on version 2.5.7 for SABnzbd.

**Comment by causalmask** [comment]
If it's going to take months to approve a fix, why wasn't 2.5.7 rolled back to 2.5.6 months ago?  Everyone attempting to install since 2.5.7 was released has had to manually roll back.

**Comment by ElDubsNZ** [comment]
Getting the same issue as others on this.

**Comment by Stoony1** [comment]
Same Problem here i will create a Bookmark for Pihole an hes say "Icon must be an image." and i dont can Create it..

**Comment by j0nnymoe** [comment]
The fix has been merged, new release has been cut, wait for the updated docker image to be built.
