### ISSUE TITLE
error for add a icon in the links

### ISSUE THREAD

**Issue by Joselito1980** [linuxserver/ifai#1183]
in the last version of Heimdall V.2.5.6.
not is possible add a icon in the links. (appears a white screen with the error "500 Internal Server Error
nginx"

**Comment by jvalrog** [comment]
getting this error too

Reverting to 2.5.5 fixed the problem for me.

**Comment by wxf158** [comment]
docker 重新拉取镜像也无法修复该问题，版本为2.5.6
