### ISSUE TITLE
php error on first connection

### ISSUE THREAD

**Issue by urbaman** [linuxserver/ifai#1187]
Hi,

I'm trying to connect to heimdall (docker, image: ghcr.io/linuxserver/heimdall), and it throws the following error:

`   Symfony\Component\ErrorHandler\Error\FatalError

  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /app/www/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /app/www/vendor/composer/ClassLoader.php(571): Whoops\Run->handleError()
#1 /app/www/vendor/composer/ClassLoader.php(571): include()
#2 /app/www/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /app/www/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements()
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}()
#6 /app/www/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter()
#7 /app/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(358): Illuminate\Support\Arr::where()
#8 /app/www/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter()
#9 /app/www/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable()
#10 /app/www/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable()
#11 /app/www/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution()
#12 /app/www/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write()
#13 /app/www/vendor/filp/whoops/src/Whoops/Run.php(370): NunoMaduro\Collision\Handler->handle()
#14 [internal function]: Whoops\Run->handleException()
#15 {main}
  thrown

  at /app/www/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
     48▕     }
     49▕
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /app/www/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /app/www/vendor/composer/ClassLoader.php(571): Whoops\Run->handleError()
#1 /app/www/vendor/composer/ClassLoader.php(571): include()
#2 /app/www/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /app/www/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements()
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}()
#6 /app/www/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter()
#7 /app/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(358): Illuminate\Support\Arr::where()
#8 /app/www/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter()
#9 /app/www/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable()
#10 /app/www/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable()
#11 /app/www/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution()
#12 /app/www/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write()
#13 /app/www/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(72): NunoMaduro\Collision\Handler->handle()
#14 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(185): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->renderForConsole()
#15 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(171): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#16 /app/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(209): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#17 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#18 {main}
  thrown in /app/www/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php on line 52
`

**Comment by jdepi** [comment]
Hi everybody,
the same issue on my installation on intranet via portainer:
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /app/www/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52

**Comment by chrismyers81** [comment]
Same here. Used the instructions from https://docs.linuxserver.io/images/docker-heimdall as a guide to set it up via portainer.

**Comment by leandromqrs** [comment]
Same error to me using Swarm and Portainer, it's happened after a server restart, lock at this:

```
Stack trace:
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #0 /app/www/vendor/composer/ClassLoader.php(571): Whoops\Run->handleError()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #1 /app/www/vendor/composer/ClassLoader.php(571): include()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #2 /app/www/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #4 /app/www/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #6 /app/www/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #7 /app/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(358): Illuminate\Support\Arr::where()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #8 /app/www/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #9 /app/www/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #10 /app/www/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #11 /app/www/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #12 /app/www/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #13 /app/www/vendor/filp/whoops/src/Whoops/Run.php(370): NunoMaduro\Collision\Handler->handle()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #14 [internal function]: Whoops\Run->handleException()
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | #15 {main}
proxy_heimdall.1.v3vdqg2gyeqc@manager01    |   thrown
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | 
proxy_heimdall.1.v3vdqg2gyeqc@manager01    |   at /app/www/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
proxy_heimdall.1.v3vdqg2gyeqc@manager01    |      48▕     }
proxy_heimdall.1.v3vdqg2gyeqc@manager01    |      49▕ 
proxy_heimdall.1.v3vdqg2gyeqc@manager01    |      50▕     protected function getCurrentBranch(string $directory): string
proxy_heimdall.1.v3vdqg2gyeqc@manager01    |      51▕     {
proxy_heimdall.1.v3vdqg2gyeqc@manager01    |   ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
proxy_heimdall.1.v3vdqg2gyeqc@manager01    |      53▕ 
proxy_heimdall.1.v3vdqg2gyeqc@manager01    |      54▕         if ($branch === "''") {
proxy_heimdall.1.v3vdqg2gyeqc@manager01    |      55▕             $branch = 'current branch';
proxy_heimdall.1.v3vdqg2gyeqc@manager01    |      56▕         }
proxy_heimdall.1.v3vdqg2gyeqc@manager01    | PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /app/www/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
```

**Comment by j0nnymoe** [comment]
First of all, these issues should be reported on the container of Heimdall, not here. Secondly, we don't support not recommend using portainer to deploy our containers and we don't test on swarm. 

Open an issue over here https://github.com/linuxserver/docker-heimdall/ - provide the details requested and someone will be able to help.

**Comment by leandromqrs** [comment]
I checked, this errors occurs because exists a sqlite db corruption, deleting him resolve this issue with succesfull (not reccommended, all your tiles and configurations is lost)
