### ISSUE TITLE
Bug: No stats on Pihole

### ISSUE THREAD

**Issue by BulldozerPete** [linuxserver/ifai#1188]
I am not able to see extended stats for Pihole.

My Pihole has got the ip: 192.168.178.2/admin

Config url: http://192.168.178.2/admin/api.php?summaryRaw
And API-key is taken from Pihole web interface.

![photo](https://github.com/linuxserver/Heimdall/assets/61943052/b16b893d-7cd5-4e8b-a50c-e331b2cce5f5)

**Comment by bratzelk** [comment]
Is that URL correct? For mine I just use `http://192.168.178.2/admin` and it works fine.

**Comment by BulldozerPete** [comment]
Now it works. Thank you!

Maybe a hint für other users would be useful too.
