### ISSUE TITLE
Bug: No stats on FritzBox

### ISSUE THREAD

**Issue by BulldozerPete** [linuxserver/ifai#1189]
How do I enable extended FritzBox stats?

![photo2](https://github.com/linuxserver/Heimdall/assets/61943052/d23312ce-5a17-4ac2-b987-180aba1b57cb)

**Comment by BulldozerPete** [comment]
Ok

**Comment by BulldozerPete** [comment]
Config needs to be updated.
TR-064 Needs to be enabled in FritzBox.

**Comment by ChrLau** [comment]
Did you get it to work @BulldozerPete? I tried enabling it, but it doesn't show any values.
The TR-064 API is active. I can retrieve the values via cURL on the command line.

When I enter my Fritzbox IP in the format of: `http://192.168.0.1` it passes the API-Test and the traffic I capture with tcpdump shows that the API-Requests to the Fritzbox are correct and answered correctly by my Fritzbox. (Ignore the message that you need a Slash at the end https://github.com/linuxserver/Heimdall-Apps/blob/master/AVMFritzbox/AVMFritzbox.php#L207 shows that this is wrong.)
Returning the same values my cURL commands give me.
https://wiki.ubuntuusers.de/FritzBox/Skripte/ has some example to start working with.

Yet no requests are done automatically when the enhanced app is viewed in the Heimdall dashoard.
Therefore the app shows nothing.

**Comment by ChrLau** [comment]
Nevermind. I got it working. Under `/path/to/Heimdall-2.5.6/storage/logs` you have the laravel logfiles.
Opening the recent one showed:

`[2023-09-18 03:45:05] local.ERROR: Call to undefined function App\SupportedApps\AVMFritzbox\simplexml_load_string() {"exception":"[object] (Error(code: 0): Call to undefined function App\\SupportedApps\\AVMFritzbox\\simplexml_load_string() at /path/to/Heimdall-2.5.6/app/SupportedApps/AVMFritzbox/AVMFritzbox.php:134)
[stacktrace]
[... message cut here, rest is irrelevant ...]`

So, yeah. The simplexml_load_string() function isn't found.. And, yep the php8.2-xml package (I'm on Raspbian) isn't installed.

```
root@raspberrypi:/path/to/Heimdall-2.5.6/storage/logs# apt-get install php8.2-xml
[...]
root@raspberrypi:/path/to/Heimdall-2.5.6/storage/logs# systemctl restart apache2
```
And it works.

**Comment by BulldozerPete** [comment]
Haven’t changed anything. Just noticed that it works now.
