### ISSUE TITLE
Slow opening speed

### ISSUE THREAD

**Issue by star2k** [linuxserver/ifai#1190]
I am using the latest version of Docker deployment, and the server performance is not low. Why is the speed of opening the homepage and backend so slow?

**Comment by hillout** [comment]
Same issue

**Comment by Velonaut** [comment]
Same Here

**Comment by cryptolukas** [comment]
Have the same problem. 
How can the problem be indentified?

**Comment by aBua-MUC** [comment]
+1 
have the same
