### ISSUE TITLE
Making tags private optional

### ISSUE THREAD

**Issue by smilebasti** [linuxserver/ifai#1193]
Hi, i just upgraded from v2.5.4 to v2.5.6 and found that tags are no longer private any more (as noted in the changelog for v2.5.5) if the dashboard is set to public.

As not discussed in #895, i on the other hand, had build my dashboard to be only partially public. I used the "bug" of having my tags private and the main page as public. Now i had to lock the whole dashboard and create a second one for my public users.

I would like to request this feature back as an option for each tag individually. This should be only visible if "Allow public access to front" is set to true. This way some tags can be set to public and some are only for user access. In my case i only need private tags and a public dashboard.

Thanks for thinking about this while reading. Hope to see this feature in the near future.

**Comment by emigrating** [comment]
Is this project completely abandoned or what's the reason every single issue or request gets marked as stale and forgot about?
