### ISSUE TITLE
Plex tile not showing details

### ISSUE THREAD

**Issue by BlueCoffee34** [linuxserver/ifai#1202]
Api connects fine, but tile does not show details from the config. Here is a few photos if more info is needed let me know

![2023-08-03 10_26_58-Heimdall - Brave](https://github.com/linuxserver/Heimdall/assets/139619582/1c99b492-e493-472f-95f6-a52bcd2b4c55)
![2023-08-03 10_26_23-Heimdall - Brave](https://github.com/linuxserver/Heimdall/assets/139619582/f3124927-18c2-428d-9687-2c7aff2777a1)
![2023-08-03 10_26_01-Heimdall - Brave](https://github.com/linuxserver/Heimdall/assets/139619582/894313dc-60bc-44de-9413-d1166b3ca2d5)

docker image = Linuxserver.io version:- v2.5.6-ls225 Build-date:- 2023-07-28T18:28:31+00:00

**Comment by Djuuu** [comment]
I worked around a similar issue, which seems related to TLS verification.

How is TLS termination in handled in your setup ? Is it only handled by Nginx Proxy, or did you also configure a custom Plex certificate ?

I found out that if you provide a "clean" proxied URL (without the 32400 Plex port), whether it be in the main "app" URL field or in the optional "config" URL field : 

* **Heimdall still uses the default 32400 Plex port in live stats requests**  
  This likely circumvents the reverse-proxy, talking to Plex directly.  
  If done using HTTPS, thins means Plex will be providing the certificate (using its default self-signed one).

* **The "skip TLS verification" toggle doesn't seem to work as intended**

--------

Example setup : 

![image](https://github.com/linuxserver/Heimdall/assets/2388233/9b371ad2-4ba5-4d58-a133-309bdb9266ed)

Here is a log extract : 
```
"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 0): 
cURL error 60: SSL: no alternative certificate subject name matches target host name 'plex.example.net'
(see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for 
https://plex.example.net:32400/library/onDeck?X-Plex-Token=secretsecretsecret 
at /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211)

[stacktrace]
#0 /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\\Handler\\CurlFactory::createRejection()
#1 /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\\Handler\\CurlFactory::finishError()
#2 /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\\Handler\\CurlFactory::finish()
#3 /app/www/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#4 /app/www/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#5 /app/www/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#6 /app/www/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#7 /app/www/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#8 /app/www/vendor/guzzlehttp/guzzle/src/Middleware.php(61): GuzzleHttp\\RedirectMiddleware->__invoke()
#9 /app/www/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#10 /app/www/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\\HandlerStack->__invoke()
#11 /app/www/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\\Client->transfer()
#12 /app/www/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\\Client->requestAsync()
#13 /app/www/app/SupportedApps.php(94): GuzzleHttp\\Client->request()
#14 /config/www/SupportedApps/Plex/Plex.php(45): App\\SupportedApps->execute()
#15 /app/www/app/Http/Controllers/ItemController.php(503): App\\SupportedApps\\Plex\\Plex->livestats()
#16 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\ItemController->getStats()
#17 /app/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#18 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#19 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#20 /app/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
...
```

Tested on version : Linuxserver.io version:- v2.5.6-ls227 Build-date:- 2023-08-11T18:28:55+00:00

--------

To circumvent this issue, you can either : 
* use HTTP in the config URL (ex: `http://plex.example.net:32400/`)
* setup your custom certificate in Plex (settings -> network)

**Comment by EHRETic** [comment]
Hi there,

I had the same issue but changing the config URL with http made it work.
Although this should not be considered as a fix! 😉

What can I provide you to help you solving that with HTTPS?

PS: in my environnement, I create custom certs with my own CA
