### ISSUE TITLE
Announcement banner

### ISSUE THREAD

**Issue by PhilippMundhenk** [linuxserver/ifai#1206]
I use Heimdall as my main portal for a number of people. It would be helpful to have to option to show a temporary announcement at the top.
Example usages would be the announcement of planned outages, new services available, or reminders and general information. 

It might be just a simple box with a given background color and complementary (or manually set) text color at the very top of the screen, stretching across the full width. 

It would be helpful to combine this banner with tags to allow it to be only shown on certain tag pages. 

One could of course add things like schedule or animations on load, but that would be much more effort and might unnecessarily complicate a neat and clean application like Heimdall.

**Comment by PhilippMundhenk** [comment]
Ping: Not stale, hasn't been touched on.

**Comment by hotrod225** [comment]
I agree. This would be nice to have. Even it popped up after login or something.

**Comment by PhilippMundhenk** [comment]
Ping: Not stale, hasn't been touched on.

**Comment by j0nnymoe** [comment]
The main developer is currently busy with work, the developer who started picking up the slack is currently missing. Hopefully when @KodeStar  has more free time he'll pick things up again, or we get some more people willing to help out.

**Comment by PhilippMundhenk** [comment]
Thanks for the hint! No worries at all, there is no hurry here. Just have to keep bumping to avoid closing as stale. Might make sense to set the bot to a lower frequency.

Also took a look how far I could get myself, but fairly quickly realized I am out of my league here...

**Comment by PhilippMundhenk** [comment]
Ping: Not stale, hasn't been touched on.

**Comment by PhilippMundhenk** [comment]
Ping: Not stale, hasn't been touched on.

**Comment by PhilippMundhenk** [comment]
Ping: Not stale, hasn't been touched on.

**Comment by j0nnymoe** [comment]
This has been touched on, I explained the situation with Heimdall here https://github.com/linuxserver/Heimdall/issues/1206#issuecomment-1761996749

**Comment by pwannenmacher** [comment]
+1

**Comment by KodeStar** [comment]
Just use the custom js or custom css settings to add any announcement banners you want, there are no plans to add anything like this in the near future, plus feature requests should be added at https://github.com/linuxserver/Heimdall/discussions/categories/ideas
