### ISSUE TITLE
no matching manifest

### ISSUE THREAD

**Issue by MacUser341** [linuxserver/ifai#1218]
I'm trying to install heimdall with portainer on Docker on my Pi.

 I'm getting an error :

“failed to deploy a stack: heimdall Pulling no matching manifest for linux/arm/v8 in the manifest list entries”

I've done everything as it says in heimdall page.

This is the stack I'm using :

---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

Can someone help me figure this out ?

**Comment by j0nnymoe** [comment]
We dropped support for 32bit https://www.linuxserver.io/blog/a-farewell-to-arm-hf

You're running a 32bit os on a 64bit board. You'll need to reinstall the is and make sure it's 64bit.

**Comment by MacUser341** [comment]
I hope there's 64bit homebridge version
