### ISSUE TITLE
500 error when tring to access public folder

### ISSUE THREAD

**Issue by flashlab** [linuxserver/ifai#1219]
I'm trying to manually install heimdall with build-in apache web server of QNAP system. The PHP Version is 8.2.0 and contains all the necessary extensions.
After extract source code in /share/Web/Heimdall，modified .env file and try to access by "http://192.168.1.22/Heimdall/public", the broswer return 500 error, and the related apache log is`ModSecurity: ModSecurity requires mod_unique_id to be installed.`
Other app needs rewrite mod through .htaccess is just fine. the env file is like:
```
APP_ENV=local
APP_KEY=base64:xxxxxxxxx
APP_DEBUG=false
APP_URL=http://localhost

LOG_CHANNEL=daily

#DB_CONNECTION=sqlite
#DB_DATABASE=app.sqlite

DB_CONNECTION=mysql
DB_HOST=localhost;unix_socket=/var/run/mariadb10.sock
#DB_PORT=<port number>
#DB_DATABASE=heimdall
#DB_USERNAME=heimdall
#DB_PASSWORD=xxxxx
```
Did I missed something? please help.

**Comment by ChrLau** [comment]
`ModSecurity: ModSecurity requires mod_unique_id to be installed`
This indicates you have mod_security installed in your Apache and mod_unique_id, a prerequisite for mod_security, is missing.

That message has nothing to do with Heimdall. It could however be the reason for the internal server error.. Try installing it or disable mod_security.
Another possible source for errors would be, that mod_security is blocking some Heimdall requests and this leads to the HTTP-500 error. See your mod_security log for that.
