### ISSUE TITLE
Portainer App Template - Failure No such Image

### ISSUE THREAD

**Issue by sk2eu** [linuxserver/ifai#1221]
Hi

What is the reason or better the solution that it does not want to find me an image ?

Failure
No such image:
linuxserver/heimdall:latest

![image](https://github.com/linuxserver/Heimdall/assets/48036204/eb922b6c-5c43-42fb-8253-be1829fff8ed)

**Comment by j0nnymoe** [comment]
Usually happens when you have DNS issues. Though we don't support nor recommend portainer for deployment of our containers.
