### ISSUE TITLE
AVM Fritzbox stats not working

### ISSUE THREAD

**Issue by johndoe0815** [linuxserver/ifai#1223]
I put in the URL of my local Fritzbox with which I can also access it, with a trailing slash:
http://192.168.178.1/

The test button of the status config does however show
"Failed: Please make sure your URL is correct and that there is a trailing slash"

The URL is correct and there is a trailing slash, so why is this not working then? I would have assumed that it needs some login details to get those statistics, but there is no more options that I can maintain for this app.

**Comment by ChrLau** [comment]
Remove the trailing slash. That's actually a bug in the documentation.
Which you can see here: https://github.com/linuxserver/Heimdall-Apps/blob/master/AVMFritzbox/AVMFritzbox.php#L207

The application takes the "http(s)://ip.ip.ip.ip"-part and adds ":49000/igdupnp/control/{$endpoint}"
With the slash you will end up with: "https://ip.ip.ip.ip/:49000/igdupnp/control/..."; and that doesn't work of course.
Without the trailing slash it will work.

**Comment by johndoe0815** [comment]
Thanks, that works!
