### ISSUE TITLE
[Enhanced App] Portainer not showing Container status

### ISSUE THREAD

**Issue by masterlog80** [linuxserver/ifai#1228]
Hello,
I have configured Portainer including the Config section (User/Pass on port 9000), and getting a confirmation:
![image](https://github.com/linuxserver/Heimdall/assets/33828929/6fc43693-0e9d-4521-b209-9a269109a9d3)
However, I am not getting any information, while checking the code on `Portainer.php`, it may show the number of Running/Stopped containers:
![image](https://github.com/linuxserver/Heimdall/assets/33828929/a9df1749-c291-4d3f-a27a-22f911efd3b8)
I have tried to follow the `Report Issue` link on the [homepage](https://apps.heimdall.site/applications/enhanced) but it seems not working as well.
Can you please take a look and confirm if I am missing something?

Regards,

**Comment by ChrLau** [comment]
Please check the laravel logfile. Most likely you are missing some PHP-Extension.
"Successfully communicated with API" only means Heimdall got an HTTP-200 when querying the URL you entered. It DOES NOT check if it can process the received data.

**Comment by masterlog80** [comment]
Hello @ChrLau,
Thank you for getting back.
> Please check the laravel logfile. Most likely you are missing some PHP-Extension.

Sorry, more details on what is and where it's that `laravel logfile` located? I have taken a look at https://laravel.com/ but I haven't really understood. 🤔 
Also, important to say, all the other *Enhanced Apps* works properly.

Regards,

**Comment by ChrLau** [comment]
Hi, the logfiles should be under: /path/to/your-heimdall-folder/storage/logs.
Like /var/www/heimdall/storage/logs.

**Comment by masterlog80** [comment]
So, you mean in at container's level. Ok, I will take a look asap.

Regards,

**Comment by masterlog80** [comment]
Hello,
I have located the logs under `/var/www/storage/logs` and the content is full of files like **lavarel-2023-10-28.log**.
Taking a look at the most recent ones, I can clearly see Errors as below:

*[2023-10-28 02:40:57] local.ERROR: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://192.168.***.***:8006/api2/json/nodes/proxmox/status {"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 0): cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://192.168.***.***:8006/api2/json/nodes/proxmox/status at /app/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211)
[stacktrace]*

After enabling **Skip TLS verification** the issue *seems* to be fixed:
![image](https://github.com/linuxserver/Heimdall/assets/33828929/d09e22f6-888d-46b6-8c50-9f64a8bf5394)

Thanks!
