### ISSUE TITLE
Mobile application editor

### ISSUE THREAD

**Issue by tito30480** [linuxserver/ifai#1229]
I can't fill the informations using mobile browser

Can you help me or fix it? 

![image](https://github.com/linuxserver/Heimdall/assets/147395687/941cd1df-c2cc-4d1b-9ddd-124fb68ffe32)

**Comment by ChrLau** [comment]
Does using your mobile in horizontal mode help? Or maybe a different browser?

Also: You included the URL to your dashboard and it's reachable for anyone. You might want to put some kind of webserver authentication in front or so.
