### ISSUE TITLE
Enhanced apps updates...

### ISSUE THREAD

**Issue by adm2k** [linuxserver/ifai#1234]
Greetings,

Was wondering how often the enhanced apps update data and if there is anyway to adjust this?

Verision 2.5.6

Also, any input on when these may be moved to enhanced?

- Proxmox backup server
- NUT UPS monitoring
- Uptime Kuma

Thanks in advance!
al...

**Comment by j0nnymoe** [comment]
They get moved to enhanced apps as and when people submit them.

**Comment by adm2k** [comment]
Thanks for letting me know.

Any thoughts on this:
Was wondering how often the enhanced apps update data and if there is anyway to adjust this?

Verision 2.5.6

**Comment by ChrLau** [comment]
From what I can see in Wireshark they update every 5 seconds. But only when the window is active. Currently this can't be configured/changed.

**Comment by aptalca** [comment]
There were some big changes recently to how frequently they update. Updates only happen when the window is active. And some schedules are dynamic. For instance, if sab is actively downloading something, the updates are frequent, but with no downloads, less frequent. I don't believe any of them are user customizable.

**Comment by adm2k** [comment]
Thanks for the responses, I appreciate it...
