### ISSUE TITLE
No Status Infos

### ISSUE THREAD

**Issue by hermann1514** [linuxserver/ifai#1236]
Hi. 

I have installed Heimdall on serveral System via Docker but have always the same Problem. I  installed the Version 2.5.6 and 2.5.7 and i can not see the Stats of the Application. So AVM Fritzbox is telling, there is an gerneral Problem with the API. I don't use the / add the End from the IP. For OpenMediaVault the API connenction is running fine, but i can't see any Status (CPU or RAM) from this. Can someone help?

Thx.
Regards
Hermann

**Comment by ChrLau** [comment]
Do the logs from the PHP Laravel Framework log something?
Should be under /path/to/your-heimdall-folder/storage/logs.

In my case it was a missing PHP package that lead to this error and the Laravel logfiles showed that PHP couldn't find some function to interpret XML data.
