### ISSUE TITLE
Enhanced apps questions...

### ISSUE THREAD

**Issue by adm2k** [linuxserver/ifai#1237]
I am new to using Heimdall, nice tool! That being said, there are three apps I would like to see in the "enhanced category". Uptime Kuma, Network UPS Tools and maybe Proxmox Backup Server.

I do have some coding skills and would be happy to work on these. Can anyone provide me some guidance or links to a guide on how to approach this?

Also, are or can links to websites (like my CUPS print server) show any sort of "alive" indicator? For example, a green button if pinged and red if ping fails. 

Here is screen shot of my current setup:
![image](https://github.com/linuxserver/Heimdall/assets/120423301/ea0a72aa-381a-425a-a0a5-64673b3e31aa)

Thanks in advance!

al...

**Comment by ChrLau** [comment]
Hi,

the Heimdall-Apps are maintained in a different Git-repository found here: https://github.com/linuxserver/Heimdall-Apps
There you'll find the basic information to get you started in the wiki: https://github.com/linuxserver/Heimdall-Apps/wiki

I'm not sure which Laravel version is currently used by Heimdall, but you'll find the Framework documentation here: https://laravel.com/docs/

**Comment by adm2k** [comment]
Thank you for the response and directions, I will proceed from here.
