### ISSUE TITLE
Portiner error

### ISSUE THREAD

**Issue by Erebus999** [linuxserver/ifai#1239]
Image name is required.

Update the Container and repull image error:
failed to pull images of the stack: heimdall Pulling no matching manifest for linux/arm/v8 in the manifest list entries

System Rapberry pi4 and Docker.
 image: lscr.io/linuxserver/heimdall:latest

**Comment by j0nnymoe** [comment]
https://info.linuxserver.io/issues/2023-04-06-armhf/
