### ISSUE TITLE
Where does the code for Bazarr live?

### ISSUE THREAD

**Issue by 4oijq342** [linuxserver/ifai#1242]
I cannot find the code for the enhanced Bazarr integration.

I want to submit a PR to it.

**Comment by 4oijq342** [comment]
I found this but it does not exist anymore: https://github.com/linuxserver/Heimdall/pull/246/files

**Comment by 4oijq342** [comment]
I am also looking for the Filebrowser integration code

**Comment by j0nnymoe** [comment]
https://github.com/linuxserver/Heimdall-Apps
