### ISSUE TITLE
I customized Heimdall's custom CSS and JS

### ISSUE THREAD

**Issue by KingKorg** [linuxserver/ifai#1249]
Hello, sorry for my english I use google translate

I customized Heimdall's custom CSS and JS, here is my code for you to adapt so that it works with your settings

![heimdall](https://github.com/linuxserver/Heimdall/assets/51614277/963acbd9-3f4d-4eeb-8639-63a1782ee58e)

[https://jsfiddle.net/8wnv1qam/](https://jsfiddle.net/8wnv1qam/)

**Comment by sudoshi** [comment]
This is beautiful work!  I will examine your code and see if I can implement for myself.  I would like to add a floating logo/emblem to the dashboard but I am not good with CSS/HTML.

**Comment by sudoshi** [comment]
![Screenshot 2023-11-25 at 8 33 17 PM](https://github.com/linuxserver/Heimdall/assets/100962480/abff21ec-c14e-454a-b365-5dc34fe13420)

I am developing this for a group of 2000+ medical researchers worldwide.

I would like to figure out how to customize the top of the page to include a logo and some other 'widgets' like @KingKorg has done.

**Comment by ghost** [comment]
Hi, would it make sense to create some sort of theme collection? (if it doesn't already exist)
