### ISSUE TITLE
i can't access Application from outside of LAN.

### ISSUE THREAD

**Issue by gerberanub** [linuxserver/ifai#1251]
https://imgur.com/a/ntyOKeb

i added Plex in dashboard.

can access plex page in home network (LAN)

but i can't not from outside of LAN.

it hangs in "http://192.168.0.20:32400/web/index.html"

please help me

**Comment by j0nnymoe** [comment]
Because heimdall doesn't proxy. You would put in an address that's accessible internally and externally.

**Comment by gerberanub** [comment]
> Because heimdall doesn't proxy. You would put in an address that's accessible internally and externally.

thank you jonny

so i  added  external address  with token  and  hit the "TEST"
it says  "General error connecting with API"

**Comment by j0nnymoe** [comment]
then your address is likely incorrect. Really you should put plex behind a reverse proxy and use that address.

**Comment by gerberanub** [comment]
i made plex behind reverse proxy and put correct address. still not working.
