### ISSUE TITLE
no Application details in Vivaldi an Brave

### ISSUE THREAD

**Issue by illbrain** [linuxserver/ifai#1256]
Hi,
after i choose an Application, i have in Vivaldi and Brave no details.
![image](https://github.com/linuxserver/Heimdall/assets/18105658/ebd9bad7-3ddd-4b3c-8d77-e2058d3075a0)

when i test it with firefox, it works. i have seen in the logfile, that this line is missing:
172.24.0.3 - - [20/Dec/2023:09:26:23 +0000] "GET /view/AdGuardHome.config HTTP/1.1"

**Comment by ericblade** [comment]
works as expected in vivaldi here ..... are you blocking javascript or something?

**Comment by illbrain** [comment]
no. neither in vivaldi nor in opera. adblockers are also disabled

Am Mi., 10. Jan. 2024 um 08:26 Uhr schrieb Eric Blade <
***@***.***>:
