### ISSUE TITLE
Import is not working correctly

### ISSUE THREAD

**Issue by styxadmin** [linuxserver/ifai#1257]
I have a previous install of Heimdall with 20 bookmarks. Due to issues with this VM I set up a new one and installed Heimdall.

I can successfully export a backup from the old Heimdall, and confirmed all bookmarks are contained within the backup.

When I run the import it shows that all bookmarks have been imported but when I navigate to the Home Dashboard, only a handful are presented.

Even on the application list it only shows the same few.

OS: Debian 12

Using Latest docker image from linuxserver

Heimdall Version: 2.5.8

![image](https://github.com/linuxserver/Heimdall/assets/50232595/7b0eef64-88c5-4976-80f6-68538bd58495)
![image](https://github.com/linuxserver/Heimdall/assets/50232595/95e807da-5e88-4e8b-996d-09c01f023924)

**Comment by burukan** [comment]
@styxadmin 

I did not have time to check the origin of this problem however temporarily I managed to import all my records via:

Option 1:
* deleted all the applications in the system
* deleted all the ones in the trash (which was cumbersome as page would go back on every delete)
* opened the downloaded export file in VSCode
* Did a Replace-All (Regex Search and Replace Enabled via [.*])
"appid": "[a-zA-Z0-9]+",
to
"appid": "null",
Imported again and all worked OK.

Option 2:
Set "appid": "null" for all the applications that do NOT import.

**BEWARE this will lose the images as appids are gone**. Looks like appid is a sha1 hash of some sort and system bugs out trying to find/merge the icon etc data. I would imagine just like me, one of your apps have either changed id or was removed from heimdall db.

Hopefully this all will be fixed soon.
