### ISSUE TITLE
Custom Search Engine

### ISSUE THREAD

**Issue by godsgood33** [linuxserver/ifai#1259]
I'd like to request to add a custom search engine.  I have Whoogle self-hosted and would like to point the search tool to my URL.  Thanks!

**Comment by j0nnymoe** [comment]
Already in the read me: https://github.com/linuxserver/Heimdall#search-providers

**Comment by godsgood33** [comment]
> Already in the read me: https://github.com/linuxserver/Heimdall#search-providers

AWESOME!!  Thanks!
