### ISSUE TITLE
Logout delay

### ISSUE THREAD

**Issue by godsgood33** [linuxserver/ifai#1265]
Is there a way to change the logout period in Heimdall so that it doesn't log you out so frequently?  I  am using Heimdall as a start/new tab page for my browser and it's frustrating to have to keep logging in every 10 mins (or whatever the increment is).  I can see doing it daily.

**Comment by KodeStar** [comment]
Session lifetime is set by default to 2 hours, you can edit the SESSION_LIFETIME in the `.env`

**Comment by godsgood33** [comment]
> Session lifetime is set by default to 2 hours, you can edit the SESSION_LIFETIME in the `.env`

@KodeStar Great, THANKS!
