### ISSUE TITLE
Sonarr config don't works

### ISSUE THREAD

**Issue by enzo-festorazzi** [linuxserver/ifai#1273]
When I try to configure Sonarr it tells me "Error: Make sure your URL is correct and there is a forward slash."

I already tried adding the slash but it doesn't solve the problem.

Heimdall: v2.5.8
Sonar: 4.0.1.929

**Comment by listiges-kaenguru** [comment]
It´s working fine for me with these settings:

![2024-02-22_13h55_48](https://github.com/linuxserver/Heimdall/assets/48389318/9a0bdebb-dbef-4014-94fa-883db9968a9d)

Can you post your settings, please?

**Comment by enzo-festorazzi** [comment]
Choose to change dashboards. Thank you so much.
