### ISSUE TITLE
Request Application to be added to the list

### ISSUE THREAD

**Issue by Simpuhl** [linuxserver/ifai#1274]
Are you able to add Whisparr to the list of applications or is it not allowed?

**Comment by KodeStar** [comment]
Already in the request list here https://apps.heimdall.site/request#b2670053bbd2b8f81c56d9b5cf038404d6ba1d9a it just needs someone to add a PR to https://github.com/linuxserver/Heimdall-Apps/ here are instructions on how to do it https://github.com/linuxserver/Heimdall-Apps/wiki/Submitting-an-app
