### ISSUE TITLE
Does not work anymore.

### ISSUE THREAD

**Issue by JFPCreations** [linuxserver/ifai#1275]
Not sure what happen, it was working great for months, but now it shows this:

From nginx reverse proxy:

@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else
{!! __('app.dash.no_apps', [ 'link1' => '['.__('app.dash.link1').'](https://heimdall.domain.com/'.route('items.create',%20[]).')', 'link2' => '['.__('app.dash.link2').'](https://heimdall.domain.com/)' ]) !!}
@include('add')
@endif @endsection

From ip.port: Login page give this:

@extends('layouts.app') @section('content')
{{ csrf_field() }}
@if($user->avatar)  @else  @endif {{ $user->username }} 
 Login
@endsection

Latest docker version of heimdall installed.

Can you help me fix this, please?

**Comment by JFPCreations** [comment]
I can still login and it show:

@extends('errors::minimal') @section('title', __('Not Found')) @section('code', '404') @section('message', __('Not Found'))

**Comment by grpfl** [comment]
Same Issue


@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else

{!! __('app.dash.no_apps', [ 'link1' => '['.__('app.dash.link1').'](http://heimdall.pacehome.org/'.route('items.create',%20[]).')', 'link2' => '['.__('app.dash.link2').'](http://heimdall.pacehome.org/)' ]) !!}
@include('add')
@endif @endsection

**Comment by diegoweb** [comment]
Same issue

`@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else
{!! __('app.dash.no_apps', [ 'link1' => '['.__('app.dash.link1').'](https://inicial.casa.brunhara.net/'.route('items.create',%20[]).')', 'link2' => '['.__('app.dash.link2').'](https://inicial.casa.brunhara.net/)' ]) !!}

@include('add')
@endif @endsection`

**Comment by moreje** [comment]
same for me... 2.5.8 and dev tags get the same error

**Comment by victorgrund** [comment]
Similar issues with the latest tag. 

@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else

{!! __('app.dash.no_apps', [ 'link1' => '['.__('app.dash.link1').'](http://heimdall.lan:32770/'.route('items.create',%20[]).')', 'link2' => '['.__('app.dash.link2').'](http://heimdall.lan:32770/)' ]) !!}
@include('add')
@endif @endsection

**Comment by SighmanSays** [comment]
Same behavior running docker from Synology.

Can work around it by using tag V2.5.8-ls251

**Comment by theyort** [comment]
Same error with the latest version. I reinstalled version 2.5.8 ls251 to return to normal operation.

**Comment by syko9000** [comment]
I'll chime in... same

**Comment by Callahan78** [comment]
same here . . .
what is the syntax to install last working version?
Tried with ":2.5.8-ls251" instead ":latest" but didn´t work.

**Comment by victorgrund** [comment]
@Callahan78, here's the top part of my docker compose file that's temporarily edited to pull a working version:
```
---
version: "2.1"
services:
  heimdall:
    #image: lscr.io/linuxserver/heimdall:latest
    image: lscr.io/linuxserver/heimdall:V2.5.8-ls251
    container_name: heimdall
```

**Comment by Callahan78** [comment]
> @Callahan78, here's the top part of my docker compose file that's temporarily edited to pull a working version:
> 
> ```
> ---
> version: "2.1"
> services:
>   heimdall:
>     #image: lscr.io/linuxserver/heimdall:latest
>     image: lscr.io/linuxserver/heimdall:V2.5.8-ls251
>     container_name: heimdall
> ```

Ah . . . I missed the "V" in "V2.5.8-ls251" . . . . now it is working :-)
Thank you very much! 👍

**Comment by JFPCreations** [comment]
Thank you.

**Comment by comfreak89** [comment]
same here. version V2.5.8-ls251 is also working for me.

**Comment by JudeLC** [comment]
Same for me

**Comment by alancarrillo** [comment]
same here. version V2.5.8-ls251 is also working for me. 
Same error with the latest version. I reinstalled version 2.5.8 ls251 to return to normal operation.

**Comment by error420** [comment]
Same here... Did we get hacked?

`@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else
{!! __('app.dash.no_apps', [ 'link1' => ''.__('app.dash.link1').'', 'link2' => ''.__('app.dash.link2').'' ]) !!}

@include('add')
@endif @endsection`

**Comment by error420** [comment]
> Same here...
> 
> `@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else {!! **('app.dash.no_apps', [ 'link1' => ''.**('app.dash.link1').'', 'link2' => ''.__('app.dash.link2').'' ]) !!}
> 
> @include('add') @endif @endsection`

Back in business by pulling the previous version of  image in portainer "lscr.io/linuxserver/heimdall:V2.5.8-ls251".

**Comment by TheLinx79** [comment]
Also broken for me. Reverting to the previous image as mentioned still give ipv6 related errors.

**Comment by OddSquirrel** [comment]
Same here, also back up running with `lscr.io/linuxserver/heimdall:V2.5.8-ls251`.

**Comment by riyadchowdhury** [comment]
Same also broken for me, I reverted to 2.5.7 which is working fine.

**Comment by mozzi75** [comment]
also not working here.

**Comment by ipod86** [comment]
Same for me

**Comment by KingKorg** [comment]
Same for me

**Comment by gladiatormax** [comment]
Here also the same.

**Comment by itinfosec** [comment]
Same problem here but reverting to ```lscr.io/linuxserver/heimdall:V2.5.8-ls251``` has worked for me

**Comment by vlemmings** [comment]
Same here on `latest`. `2.5.7` seems to be working fine.

**Comment by Tagiwara** [comment]
same hier... 2.5.7 works well... 2.5.8 returns an error as shown above

**Comment by Fooose** [comment]
Same for me.

**Comment by OrbitingOcelot** [comment]
God and I thought it was my server upgrade that broke it spent half an hour trying to find the issue...

**Comment by jamesanderson9182** [comment]
me too

**Comment by xxcriticxx** [comment]
Who broke heimdall?

**Comment by xabix** [comment]
Same issue here!

**Comment by pshdomo** [comment]
+1. Same issue

**Comment by mrxxxxxx** [comment]
exact same Issue. Back to V2.5.8-ls251

**Comment by cibercue** [comment]
Thanks, back to V2.5.8-ls251 and works.

**Comment by m3tc0n** [comment]
Same here, back to V2.5.8-ls251 and it works again.

**Comment by Fawlty65** [comment]
Same here. Reverted back.

**Comment by juhnu1** [comment]
Same here, reverted. Thx guys

**Comment by cammelspit** [comment]
Same issue, gonna revert now, at least it isnt just me!

**Comment by sunfang1cn** [comment]
Same issue

**Comment by ppfeufer** [comment]
If you are affected by this issue, please just "upvote" the [opening post](https://github.com/linuxserver/Heimdall/issues/1275#issue-2139431831). Posting here "Same issue" all the time is just spamming various mailboxes of people who follow this issue. I'm pretty sure the devs got the message by now.

This is also resulting in this, which is indeed not helpful:

![image](https://github.com/linuxserver/Heimdall/assets/2989985/99c8dd91-b630-4799-bc20-a99a62c6a7a2)


If you want to get updates on this issue, you can subscribe to it.

Thank you.

**Comment by WildStar2022** [comment]
I run Heimdall on Kubernetes (MicroK8s on Ubuntu) in a VM and manage applications using Portainer CE.

Make sure to backup first or make a snapshot if running Heimdall in a VM!
Consult Portainer docs if using Helm, Docker, or want to use the command line.

-  Login to Portainer
-  Select the Kubernetes environment
-  From the Dashboard, select Applications
-  From the Applications list, select heimdall (or whatever you called it)
-  From the Applications details, select YAML
-  Select Copy to clipboard
-  Paste to an editor like Notepad
-  From your editor:
       - Comment out:  #image: linuxserver/heimdall:latest
       - Replace with: image: linuxserver/heimdall:V2.5.8-ls251
       - Edit/Select All then Copy    
-  From your browser Portainer window, go back one page 
-  Select Create from manifest
-  Toggle User namespace(s) specified from manifest
-  I left Namespace to default
-  Enter heimdall (or whatever you called it) in the Name field
-  Select Web Editor and Paste the contents of your clipboard
-  Finally at the bottom under Action, select Deploy

**Comment by rasfincher** [comment]
I'm using Portainer on a Synology and rolling back go V2.5.8-ls251 did not resolve the issue for me. Rolling back to V2.5.7-ls238 works for me.

**Comment by elax46** [comment]
I have the same problem on my instance too

**Comment by underwoodblog** [comment]
same here via docker on debian. switched from latest to 2.5.7 to get it running again.

**Comment by BugFixer300** [comment]
@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else

{!! __('app.dash.no_apps', [ 'link1' => '['.__('app.dash.link1').'](http://192.168.1.13:8056/'.route('items.create',%20[]).')', 'link2' => '['.__('app.dash.link2').'](http://192.168.1.13:8056/)' ]) !!}
@include('add')
@endif @endsection

Same thing

**Comment by j0nnymoe** [comment]
Pinned the issue and I'm just going to lock the conversation for now. We are aware of the issue, as mentioned by @ppfeufer - this is getting spammy right now. We are working on a fix, just roll back to the previous tag that's been mentioned already.

**Comment by KodeStar** [comment]
This should be fixed. Additionally I'll be dropping a new release v2.6.0 tomorrow, if anyone has a chance please test it using the `:development` tag. The new release updates the underlying framework from Laravel 8 to Laravel 10, which increases the minimum php version to 8.1 as well as requiring the DOM PHP extension and adds in Search support on the application dropdown list.
