### ISSUE TITLE
Missing icon ? Unifi

### ISSUE THREAD

**Issue by tablatronix** [linuxserver/ifai#1279]
https://appslist.heimdall.site/icons/unifi.png

**Comment by KodeStar** [comment]
Not an issue. The icon has been updated to an SVG, you just need to click on the update apps list button to update the list. 
<img width="172" alt="image" src="https://github.com/linuxserver/Heimdall/assets/5698566/32def5d7-2986-4d6a-97a9-4cd44445cbd7">
