### ISSUE TITLE
apps.heimdall.site does not show all applications

### ISSUE THREAD

**Issue by imnotjames** [linuxserver/ifai#1303]
Not sure if there's a better place to report this - if so let me know, I can open there.

the apps.heimdall.site foundation apps listing stops at RStudio server -- so it seems it has a limit of 205 being displayed when there are 315 non-enhanced apps and it stops in the "R"s -- so apps like transmission or scrutiny are not displayed.  This also applies to the enhanced apps, so I think it's just ALL apps are cut off around the Rs.

**Comment by imnotjames** [comment]
Still an issue, unfortunately.  I'd be happy to support but I'm not sure where the code for the server is.

**Comment by KodeStar** [comment]
Should be fixed, it didn't like the app RompЯ and that was crashing it out. I've just got it skipping over any it can't handle for now.
