### ISSUE TITLE
Unable to re-order when Tags as Categories selected

### ISSUE THREAD

**Issue by lloydbayley** [linuxserver/ifai#1309]
G'day!

Am I missing the obvious or is this a problem? I have the Tags As Categories selected from the recent update.
However, I cannot reorder things whilst this mode is in use.

Cheers!

**Comment by canetex** [comment]
Yes I Have the same issu here.

**Comment by lloydbayley** [comment]
I'm glad it's not just me! :) I'm sure they will look at it in due course.

**Comment by oojroo** [comment]
To get the ordering within tag categories you need to do switch "treat tags as" to tags, do the ordering and then switch back to categories.

**Comment by KodeStar** [comment]
Click on the title, then you can reorder the individual items

**Comment by rbrussell82** [comment]
> Click on the title, then you can reorder the individual items

Can confirm this works.  Click on the title of the category, then you can click Re-Order on that page and the settings will save.

**Comment by lloydbayley** [comment]
Well blimey! That was well-hidden. Thanks everyone. I would have thought it would activate with the re-order nonetheless, however, I see now that it is column-specific.
