### ISSUE TITLE
PWA Support 

### ISSUE THREAD

**Issue by EnArvy** [linuxserver/ifai#1320]
Hi
It would be nice to have installable pwa support. Currently my solution is to add a manifest.json using Custom JS option to head and it 'works', but it would be better to have native support with caching etc implemented.

**Comment by esbeeb** [comment]
I for one, use the "Add to Home Screen" on Android.

Interestingly, Firefox (on both desktop and Android) *will* show a stale, yet somewhat-functional heimdal, persisting across opening and closing Firefox _as long as the refresh button is not pressed_. *I keep Heimdal pinned in Firefox for this reason*. I've used this trick many a time for when the Heimdal server unexpectedly goes down for a while, allowing Heimdal to still work.

I would like a PWA as well (not trivial to code), but can live without it well enough.
