### ISSUE TITLE
ERROR on Login - Runtime Exception PHP 8.3.6 10.44.0 This password does not use the Bcrypt algorithm.

### ISSUE THREAD

**Issue by AbhiOommen** [linuxserver/ifai#1330]
Getting the below error on login to the app, as docker on UnRaid.

`app/Http/Controllers/Auth/LoginController.php: 79

    {

        $current_user = User::currentUser();

        $request->merge(['username' => $current_user->username, 'remember' => true]);

        //die(print_r($request->all()));

        $this->validateLogin($request);

        // If the class is using the ThrottlesLogins trait, we can automatically throttle

        // the login attempts for this application. We'll key this by the username and

        // the IP address of the client making these requests into this application.

        if ($this->hasTooManyLoginAttempts($request)) {

            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);

        }

        if ($this->attemptLogin($request)) {     

            return $this->sendLoginResponse($request);

        }

        // If the login attempt was unsuccessful we will increment the number of attempts

        // to login and redirect the user back to the login form. Of course, when this

        // user surpasses their maximum number of attempts they will get locked out.

        $this->incrementLoginAttempts($request);

        return $this->sendFailedLoginResponse($request);

    }

    public function index()

    {

    }`

if ($this->attemptLogin($request))  - is the line with the error.

**Comment by martonsz** [comment]
This helped me. It removes the password for the admin user by creating an empty password with the Bcrypt algorithm.

```shell
# run artisian with the argument 'tinker'
./artisan tinker

# run the following commands. Including the dollar signs:
$user = App\User::where('id', 1)->first();
$user->password = Hash::make('password');
$user->save();

# press ctrl+d to quit
```

If you cant find artisian try searching for it

`find / -name artisan  2>/dev/null`
