### ISSUE TITLE
Autofocus on search bar

### ISSUE THREAD

**Issue by gbnk0** [linuxserver/ifai#1333]
Hi,
It will be good to have an option to autofocus on the search bar when enabled.
Regards

**Comment by aptalca** [comment]
That creates a horrible user experience on mobile as it fires up the on screen keyboard that covers half the screen

**Comment by gbnk0** [comment]
Then an option to enable/disable this feature will be good. Or detect mobile by checking the user agent is possible ? No?
Regards

**Comment by gbnk0** [comment]
How homarr does?
