### ISSUE TITLE
Sort order of entries not maintained with multiple tags

### ISSUE THREAD

**Issue by etrigan63** [linuxserver/ifai#1337]
After painstakingly arranging my links in alphabetical order under each tag (which is also sorted in alpha order), I have discovered that entries with multiple tags are moving out of order in both tags.

You will need to store the order of entries under each tag separately. This will also allow that tags/entries be sorted by various criteria (DESCRIPTION being the most obvious).

I am running the latest version (2.6.1) on TrueNAS SCALE Dragonfish

**Comment by martijnw** [comment]
I noticed this today too. When a link has multiple tags, moving it in one tag will also move it in the other tag.
