### ISSUE TITLE
DuckDuckGo Captcha

### ISSUE THREAD

**Issue by kpurintun** [linuxserver/ifai#1338]
Wondering if this is just me, or a new thing that DuckDuckGo is doing, but when I use the search bar in Heimdall, I always have to find 3 ducks before I can continue.

I am not sure if this is a new DDG feature that I have to deal with or if there is anything I can do to avoid that.  

I can just use the address bar which does not have the same issue.

**Comment by DuaneR5280** [comment]
I'm running into this as well. My stack is behind a wiregaurd VPN using PIA. 

This also happens with other search providers like google and bing.

**Comment by j0nnymoe** [comment]
The captcha will be due to your VPN connection, not anything to do with Heimdall.

**Comment by DuaneR5280** [comment]
> The captcha will be due to your VPN connection, not anything to do with Heimdall.

I figured as much, are there any search providers that use an API key that would work behind my VPN and not throw a captcha?

**Comment by j0nnymoe** [comment]
The reason it's happening is because the IP of your VPN server you're using has a bad reputation.

**Comment by 5280Pipedream** [comment]
I understand why it's happening. I'm looking for a way to keep my search queries behind my VPN and still use search from Heimdall. 
I can connect to my VPN and use search from my PC without this happening over and over again. This was also working fine behind my VPN with Heimdall for years.

**Comment by DuaneR5280** [comment]
> The reason it's happening is because the IP of your VPN server you're using has a bad reputation.

I actually removed this container from the VPN network. I've verified it's using my home network IP. I'm having to enter captcha every single time I use search. Changing providers also uses a captcha.

I can search from my local PC(s) browsers without having to captcha every single time.

**Comment by j0nnymoe** [comment]
Ah ok fair - maybe they're requiring additional information now when submitting a search.

**Comment by DuaneR5280** [comment]
> Ah ok fair - maybe they're requiring additional information now when submitting a search.

I'm not sure, I just repeatedly spammed the search and it stopped requiring the captcha after two submittals. The other search providers (google, bing) didn't hit a captcha actually. It seems random. Not a big deal, I just wanted to chime in that I'm getting this as well. Mostly an issue I ignore for now.

**Comment by kpurintun** [comment]
> The captcha will be due to your VPN connection, not anything to do with Heimdall.

I am not using a VPN.  If I search through Heimdall (DDG), captcha...  if I search through the address bar (DDG), no captcha...  if I search through DDG, no captcha...

**Comment by kpurintun** [comment]
> > Ah ok fair - maybe they're requiring additional information now when submitting a search.
> 
> I'm not sure, I just repeatedly spammed the search and it stopped requiring the captcha after two submittals. The other search providers (google, bing) didn't hit a captcha actually. It seems random. Not a big deal, I just wanted to chime in that I'm getting this as well. Mostly an issue I ignore for now.

I just tried spamming it with 12 searches, each asked for a captcha.  I can search DDG anywhere else.  from the browser bar, from any browser, from inside the DDG website without captcha.  But if I use the Heimdall search bar, its captcha every time.
