### ISSUE TITLE
Reordering of apps doesn't work when using categories.

### ISSUE THREAD

**Issue by vrelk-net** [linuxserver/ifai#1358]
When having "Treat Tags As" set to categories, you are unable to reorder apps inside the categories by dragging them. You are able to move the entire category around though.
I did notice that if you switch back to folders or tags, then reorder the apps, then switch back to categories, the order of the apps will change.

Version 2.6.1

**Comment by magiceupho** [comment]
Hi,
The search by tiles doesn't work either with tags as categories.

**Comment by vrelk-net** [comment]
Bump

**Comment by KodeStar** [comment]
For the reordering, click on the category title, then you can reorder

**Comment by magiceupho** [comment]
@KodeStar you can only reorder categories, not each apps that are in the categories !
We would like to reorder all the apps in the categories.
And the problem with the search by tiles is always here.

**Comment by KodeStar** [comment]
As I said... Click on the category title, that will then list the apps in that category, which you can then re-order, which will reorder them on the homepage as well. Create a new ticket for unrelated issues, thanks.

**Comment by KodeStar** [comment]
#1386
