### ISSUE TITLE
Installing Custom Apps: Could not open input file: artisan

### ISSUE THREAD

**Issue by ThunderTechnologies** [linuxserver/ifai#1359]
I apologize if this is really simple or obvious. I've searched and have been unable to find a solution (and php is not my strong suit)

I've installed Heimdall (2.6.1) within docker on an ubuntu (22.04) server following these instructions:
[https://github.com/linuxserver/Heimdall/discussions/778](url)

Now I'm trying to add an Enhanced App (specifically the APCUPSD app). I'm using these instructions:
[https://home-automation-india.github.io/docker-and-self-hosted-apps/heimdall/](url)

When I get to step 6 and run:
`php artisan register:app APCUPSDUPSNetworkMonitor`
I get the result:
`Could not open input file: artisan`

Any help on this would be greatly appreciated.

**Comment by LordSexy** [comment]
I found my artisan file in /app/www

so use

```
cd /app/www
php artisan register:app APCUPSDUPSNetworkMonitor
```

It worked for though

**Comment by KodeStar** [comment]
If there is an enhanced app available it will already be in the list, downloading just generates a template for someone to create an enhanced app, it isn't an enhanced app by itself.
