### ISSUE TITLE
ajouter de nouvelles applications préconfigurées

### ISSUE THREAD

**Issue by juangomes376** [linuxserver/ifai#1365]
I had already configured mine and I'm loving using it, but I would like to add some apps that are not on the list to download the icons automatically, and I'm a little blocked to do this because I found the file "supportedapps.json" that has the list of apps but I didn't understand 2 things: where the "appid" comes from and if there is a way to pass a physical address to the logo because I saw in the browser that it downloads from a website, How can I add new apps to this list???

**Comment by KodeStar** [comment]
https://apps.heimdall.site/ and https://github.com/linuxserver/Heimdall-Apps/wiki/Submitting-an-app should get you there
