### ISSUE TITLE
Stopped workig

### ISSUE THREAD

**Issue by redlingg** [linuxserver/ifai#1367]
Hello
I have debian and OMV6 on PI4 4GB. Heimdall was intsallled via Portainer for couple of years, now it stopped working. Tried to reinstall, nothing changed.
Stack:
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /srv/dev-disk-by-uuid-08E432AFE4329EBE/Data/Config:/config
    ports:
      - 81:80
      - 443:443
    restart: unless-stopped

LOG:
New container detected, installing Heimdall
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2018-03-06 │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
│            │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...

What should I do?

**Comment by KodeStar** [comment]
This is probably better asked at https://github.com/linuxserver/docker-heimdall/issues as it is a docker issue rather than software.
