### ISSUE TITLE
Minor comment about Pinned

### ISSUE THREAD

**Issue by RichardUUU** [linuxserver/ifai#137]
The word "pinned" threw me for a bit. I usually think of "pinned" as being attached to something, as in pinned to a certain page, etc. Best I can figure, in Heimdall, pinned basically means "visible." Perhaps you might call it that. Or maybe I completely misunderstand.

**Comment by KodeStar** [comment]
well it means pinned to the dashboard, the apps are still visible in the list page.

**Comment by RichardUUU** [comment]
Thanks. That's the problem with UI. You never know when someone will get the wrong end of the stick.

**Comment by KodeStar** [comment]
Indeed, and not everyone is a native english speaker, making it even harder, I'll have a think if there is a way to make it clearer.

**Comment by RichardUUU** [comment]
FWIW, logically, the default would be for apps to show in the dashboard, since presumably that is why they are added. So perhaps the action of the slider should be to "Hide This App"
