### ISSUE TITLE
Proxmox Backup Server throwing error

### ISSUE THREAD

**Issue by yanne057** [linuxserver/ifai#1373]
I have added Proxmox Backup Server to the SupportedApps folder and have enabled it with `php artisan register:app ProxmoxBackupServer`. I have downloaded the Enhanced Version.
When i configure the API in Heimdall i'm getting the error: "Something went wrong: { "message": "Server Error" }

Have i done something wrong or how can i fix this?

**Comment by KodeStar** [comment]
If Proxmox Backup Server is available as an enhanced app it will just work. Downloading just generates a template for someone to create an enhanced app to then submit it for PR

**Comment by yanne057** [comment]
That means that PBS isn't an enhanced app, but just a template?
Because i cant find it in the Apps List
