### ISSUE TITLE
nginx: [emerg] invalid port in resolver "fe80::1%wlp1s0" in /config/nginx/resolver.conf:3

### ISSUE THREAD

**Issue by lishx8888** [linuxserver/ifai#1380]
nginx: [emerg] invalid port in resolver "fe80::1%wlp1s0" in /config/nginx/resolver.conf:3

**Comment by KodeStar** [comment]
Not a software issue, add an issue here https://github.com/linuxserver/docker-heimdall/issues if you haven't fixed it.
