### ISSUE TITLE
cURL error 6: Could not resolve host: appslist.heimdall.site (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by erich-maier** [linuxserver/ifai#1381]
Hello Linusserver-Team,

I try to install heimdall on a Synology docker instance. By activating, I got this message in the protocol.

cURL error 6: Could not resolve host: appslist.heimdall.site (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

The website appslist.heimdall.site -> 404 ... It looks like, the website is offline.

Kind Regard

**Comment by KodeStar** [comment]
404 doesn't indicate the website is offline, it indicates what you hit doesn't exist, which is correct, there is nothing at the root, check https://appslist.heimdall.site/list.json.
