### ISSUE TITLE
Config (Optional) not available on edit

### ISSUE THREAD

**Issue by deatharse** [linuxserver/ifai#168]
Using the latest docker image If you add an app e.g. Pihole and do nothing with the Optional config setting URL / Enable, these are not available when you edit so you must either
- Reselect the App Name
- Delete and re-add the app.

Also if you do not specify a URL once the validation fires to state `The url field is required.` it disappears.

The same happens with NZBGet.

**Comment by KodeStar** [comment]
Should be fixed, if not in current release (though I think it is) it's fixed in 2.1.0 as the way it works has changed
