### ISSUE TITLE
[i18n] Missing translations BR

### ISSUE THREAD

**Issue by keriati** [linuxserver/ifai#958]
The following translations are missing from the br translation file:

        "settings.advanced": "Advanced",
        "settings.custom_css": "Custom CSS",
        "settings.custom_js": "Custom JavaScript",
        "options.nzbhydra": "NZBHydra",
        "options.jackett": "Jackett",
        "buttons.downloadapps": "Update Apps List",
        "apps.preview": "Preview",
        "apps.apptype": "Application Type",
        "apps.website": "Website",
        "apps.description": "Description",
        "apps.only_admin_account": "Only if you have admin-account!",
        "apps.autologin_url": "Auto login url",
        "apps.show_deleted": "Showing Deleted Applications",
        "dashboard": "Home dashboard",
        "alert.success.updating": "Updating apps list"

**Comment by filipefumaux** [comment]
I can take this one.
