### ISSUE TITLE
[i18n] Missing translations ES

### ISSUE THREAD

**Issue by keriati** [linuxserver/ifai#961]
Missing translation form the ES language file:

        "settings.advanced": "Advanced",
        "settings.support": "Support",
        "settings.donate": "Donate",
        "settings.window_target": "Link opens in",
        "settings.window_target.current": "Open in this tab",
        "settings.window_target.one": "Open in the same tab",
        "settings.window_target.new": "Open in a new tab",
        "settings.custom_css": "Custom CSS",
        "settings.custom_js": "Custom JavaScript",
        "options.startpage": "StartPage",
        "options.nzbhydra": "NZBHydra",
        "buttons.downloadapps": "Update Apps List",
        "apps.apikey": "API Key",
        "apps.enable": "Enable",
        "apps.tag_list": "Tags list",
        "apps.add_tag": "Add tag",
        "apps.tag_name": "Tag name",
        "apps.tags": "Tags",
        "apps.override": "If different to main url",
        "apps.preview": "Preview",
        "apps.apptype": "Application Type",
        "apps.website": "Website",
        "apps.description": "Description",
        "apps.only_admin_account": "Only if you have admin-account!",
        "apps.autologin_url": "Auto login url",
        "apps.show_deleted": "Showing Deleted Applications",
        "dashboard": "Home dashboard",
        "user.user_list": "Users",
        "user.add_user": "Add user",
        "user.username": "Username",
        "user.avatar": "Avatar",
        "user.email": "Email",
        "user.password_confirm": "Confirm Password",
        "user.secure_front": "Allow public access to front - Only enforced if a password is set.",
        "user.autologin": "Allow logging in from a specific URL. Anyone with the link can login.",
        "alert.success.updating": "Updating apps list",
        "alert.success.tag_created": "Tag created successfully",
        "alert.success.tag_updated": "Tag updated successfully",
        "alert.success.tag_deleted": "Tag deleted successfully",
        "alert.success.tag_restored": "Tag restored successfully",
        "alert.success.user_created": "User created successfully",
        "alert.success.user_updated": "User updated successfully",
        "alert.success.user_deleted": "User deleted successfully",
        "alert.success.user_restored": "User restored successfully"

**Comment by olafrv** [comment]
I checked this to be aligned with the terms that were already being used: 
https://github.com/linuxserver/Heimdall/blob/2.x/resources/lang/es/app.php

I see some corrections (as in spanish connectors like "de" aren't capitalized):
```
    'settings.background_image' => 'Imagen de Fondo',
    'settings.homepage_search' => 'Página de Inicio de Búsqueda',
```
Here the translations for the new ones:
```
    "settings.advanced": "Avanzada",
    "settings.support": "Soporte",
    "settings.donate": "Donar",
    "settings.window_target": "Vínculo abre en",
    "settings.window_target.current": "Abrir en ésta pestaña",
    "settings.window_target.one": "Abrir en la misma pestaña",
    "settings.window_target.new": "Abrir en una nueva pestaña",
    "settings.custom_css": "CSS Personalizado",
    "settings.custom_js": "JavaScript Personalizado",
    "options.startpage": "Página de Inicio",
    "options.nzbhydra": "NZBHydra",
    "buttons.downloadapps": "Actualizar lista de Applicaciones",
    "apps.apikey": "Clave de API",
    "apps.enable": "Habilitar",
    "apps.tag_list": "Lista de Etiquetas",
    "apps.add_tag": "Añadir Etiqueta",
    "apps.tag_name": "Nombre de Etiqueta",
    "apps.tags": "Etiquetas",
    "apps.override": "Si es differente de la URL principal",
    "apps.preview": "Previsualizar",
    "apps.apptype": "Tipo de Aplicación",
    "apps.website": "Sitio Web",
    "apps.description": "Descripción",
    "apps.only_admin_account": "¡Solo si tienes cuenta de administrador!",
    "apps.autologin_url": "URL de auto inicio de sessión",
    "apps.show_deleted": "Mostrando Aplicaciones Eliminadas",
    "dashboard": "Tablero Inicial",
    "user.user_list": "Usuarios",
    "user.add_user": "Añadir Usuario",
    "user.username": "Nombre de Usuario",
    "user.avatar": "Avatar",
    "user.email": "Correo Electrónico",
    "user.password_confirm": "Confirmar Contraseña",
    "user.secure_front": "Permitir acceso público a la interfaz - Forzado solo si una contraseña está definida.",
    "user.autologin": "Permitir inicio de sesión desde una URL específica. Cualquiera con el vínculo puede iniciar sesión.",
    "alert.success.updating": "Actualizando lista de aplicaciones",
    "alert.success.tag_created": "Etiqueta creada exitósamente",
    "alert.success.tag_updated": "Etiqueta actualizada exitósamente",
    "alert.success.tag_deleted": "Etiqueta eliminada exitósamente",
    "alert.success.tag_restored": "Etiqueta restaurada exitósamente",
    "alert.success.user_created": "Usuario creado exitósamente",
    "alert.success.user_updated": "Usuario actualizado exitósamente",
    "alert.success.user_deleted": "Usuario eliminado exitósamente",
    "alert.success.user_restored": "Usuario restaurado exitósamente"
```
Regarding NZBHydra if related to this: https://github.com/theotherp/nzbhydra2, better to keep it as it is (untranslated).

Let me know if you need more help with Spanish translations.

**Comment by keriati** [comment]
Thanks, I will add it soon.
