### ISSUE TITLE
Larger background resolution

### ISSUE THREAD

**Issue by Forsskieken** [linuxserver/ifai#976]
I guess when one uploads a background, the resolution is saved at 1600x1200. However some of us have larger monitors  and even when one uploads a 4K background image the upper part off the image is cuttoff when used as a background for Heimdall.

**Comment by keriati** [comment]
Uploaded backgrounds are saved at original resolution, there is no resizing to 1600x1200.
Background is positioned in a way that it covers the whole screen, this means depending on the browser window size it has to cut off the top and bottom or left and right sides.
